In [2]:
import pandas as pd

c:\Users\riven\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\riven\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\riven\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [4]:
recommendation = pd.read_csv('recommendations-2021-12-31.csv',sep=',')
games = pd.read_csv('bgg_Gameitems.csv',sep=',')

In [ ]:
recommendation.head()

,ID,Name,Year,Rank,Average,Bayes average,Users rated,URL,Thumbnail,recommendation1,...,recommendation19,recommendation20,recommendation21,recommendation22,recommendation23,recommendation24,recommendation25,recommendation26,recommendation27,recommendation28
0,174430,Gloomhaven,2017,1,8.74,8.511,47555,/boardgame/174430/gloomhaven,https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZ...,291457,...,271896.0,195421.0,285192.0,316554.0,233078.0,170216.0,187645.0,121921.0,169426.0,302723.0
1,161936,Pandemic Legacy: Season 1,2015,2,8.60,8.444,44877,/boardgame/161936/pandemic-legacy-season-1,https://cf.geekdo-images.com/-Qer2BBPG7qGGDu6K...,221107,...,195421.0,174430.0,181304.0,201808.0,255984.0,178900.0,259081.0,156129.0,169786.0,284083.0
2,224517,Brass: Birmingham,2018,3,8.67,8.417,25216,/boardgame/224517/brass-birmingham,https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg...,220308,...,321608.0,182028.0,229853.0,161533.0,311193.0,359438.0,342942.0,142379.0,124361.0,233398.0
3,167791,Terraforming Mars,2016,4,8.42,8.273,73742,/boardgame/167791/terraforming-mars,https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZ...,341169,...,229853.0,276025.0,236457.0,84876.0,251247.0,164928.0,328871.0,262712.0,266810.0,173346.0
4,233078,Twilight Imperium: Fourth Edition,2017,5,8.68,8.260,15911,/boardgame/233078/twilight-imperium-fourth-edi...,https://cf.geekdo-images.com/_Ppn5lssO5OaildSE...,246900,...,291572.0,189932.0,253499.0,103343.0,162886.0,299659.0,181279.0,37111.0,397598.0,39463.0

In [5]:



# create new column for family with just the string before the first period
games['sim_family'] = games['family'].str.split(':').str[0]

In [ ]:
games_num = games.select_dtypes(include=['int64', 'float64'])

In [6]:
merged_df = pd.merge(recommendation,games, how='left', left_on='ID', right_on='bgg_id')

In [7]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 75 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   1000 non-null   int64
 1   Name                 1000 non-null   object
 2   Year                 1000 non-null   int64
 3   Rank                 1000 non-null   int64
 4   Average              1000 non-null   float64
 5   Bayes average        1000 non-null   float64
 6   Users rated          1000 non-null   int64
 7   URL                  1000 non-null   object
 8   Thumbnail            1000 non-null   object
 9   recommendation1      1000 non-null   int64
 10  recommendation2      1000 non-null   int64
 11  recommendation3      1000 non-null   int64
 12  recommendation4      1000 non-null   int64
 13  recommendation5      1000 non-null   int64
 14  recommendation6      1000 non-null   int64
 15  recommendation7      669 non-null    float64
 16  recommendation8      668 non-null    float64
 17  recommendation9      668 non-null    float64
 18  recommendation10     668 non-null    float64
 19  recommendation11     668 non-null    float64
 20  recommendation12     668 non-null    float64
 21  recommendation13     668 non-null    float64
 22  recommendation14     668 non-null    float64
 23  recommendation15     667 non-null    float64
 24  recommendation16     667 non-null    float64
 25  recommendation17     667 non-null    float64
 26  recommendation18     667 non-null    float64
 27  recommendation19     667 non-null    float64
 28  recommendation20     667 non-null    float64
 29  recommendation21     667 non-null    float64
 30  recommendation22     666 non-null    float64
 31  recommendation23     666 non-null    float64
 32  recommendation24     666 non-null    float64
 33  recommendation25     666 non-null    float64
 34  recommendation26     665 non-null    float64
 35  recommendation27     665 non-null    float64
 36  recommendation28     665 non-null    float64
 37  bgg_id               1000 non-null   int64
 38  name                 1000 non-null   object
 39  year                 1000 non-null   float64
 40  game_type            999 non-null    object
 41  artist               968 non-null    object
 42  publisher            1000 non-null   object
 43  min_players          1000 non-null   float64
 44  max_players          1000 non-null   float64
 45  min_players_rec      1000 non-null   float64
 46  max_players_rec      1000 non-null   float64
 47  min_players_best     1000 non-null   float64
 48  max_players_best     1000 non-null   float64
 49  min_age              998 non-null    float64
 50  min_age_rec          735 non-null    float64
 51  min_time             999 non-null    float64
 52  max_time             999 non-null    float64
 53  category             998 non-null    object
 54  mechanic             1000 non-null   object
 55  cooperative          145 non-null    float64
 56  compilation          6 non-null      float64
 57  compilation_of       6 non-null      object
 58  family               993 non-null    object
 59  implementation       220 non-null    object
 60  integration          173 non-null    object
 61  rank                 999 non-null    float64
 62  num_votes            1000 non-null   float64
 63  avg_rating           1000 non-null   float64
 64  stddev_rating        1000 non-null   float64
 65  bayes_rating         1000 non-null   float64
 66  complexity           999 non-null    float64
 67  language_dependency  550 non-null    float64
 68  bga_id               0 non-null      float64
 69  dbpedia_id           0 non-null      float64
 70  luding_id            0 non-null      float64
 71  spielen_id           0 non-null      float64
 72  wikidata_id          0 non-null      float64
 73  wikipedia_id         0 non-null      float64
 74  sim_family           993 non-null    object
dtypes: float64(50), int64(11), object(14)
memory usage: 593.8+ KB

In [8]:
merged_df = merged_df.dropna(thresh=990, axis=1)

In [9]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1000 non-null   int64
 1   Name              1000 non-null   object
 2   Year              1000 non-null   int64
 3   Rank              1000 non-null   int64
 4   Average           1000 non-null   float64
 5   Bayes average     1000 non-null   float64
 6   Users rated       1000 non-null   int64
 7   URL               1000 non-null   object
 8   Thumbnail         1000 non-null   object
 9   recommendation1   1000 non-null   int64
 10  recommendation2   1000 non-null   int64
 11  recommendation3   1000 non-null   int64
 12  recommendation4   1000 non-null   int64
 13  recommendation5   1000 non-null   int64
 14  recommendation6   1000 non-null   int64
 15  bgg_id            1000 non-null   int64
 16  name              1000 non-null   object
 17  year              1000 non-null   float64
 18  game_type         999 non-null    object
 19  publisher         1000 non-null   object
 20  min_players       1000 non-null   float64
 21  max_players       1000 non-null   float64
 22  min_players_rec   1000 non-null   float64
 23  max_players_rec   1000 non-null   float64
 24  min_players_best  1000 non-null   float64
 25  max_players_best  1000 non-null   float64
 26  min_age           998 non-null    float64
 27  min_time          999 non-null    float64
 28  max_time          999 non-null    float64
 29  category          998 non-null    object
 30  mechanic          1000 non-null   object
 31  family            993 non-null    object
 32  rank              999 non-null    float64
 33  num_votes         1000 non-null   float64
 34  avg_rating        1000 non-null   float64
 35  stddev_rating     1000 non-null   float64
 36  bayes_rating      1000 non-null   float64
 37  complexity        999 non-null    float64
 38  sim_family        993 non-null    object
dtypes: float64(18), int64(11), object(10)
memory usage: 312.5+ KB

In [10]:
merged_df = merged_df.dropna()

In [12]:
merged_df.to_csv('cleaned data ver 1.csv', index=False)

In [ ]:
game_type = merged_df['game_type'].str.get_dummies()

In [ ]:
#get dummies for game type. A game could belong to multiple types. The game_type column is a string with multiple types separated by commas
games_type = merged_df['game_type'].str.get_dummies(sep=',')

In [ ]:
games_type.columns

Index(['Abstract Game', 'Children's Game', 'Customizable', 'Family Game',
       'Party Game', 'Strategy Game', 'Thematic', 'War Game'],
      dtype='object')